/**
 * Outbox & Offline Queued Operations
 * Ensures transactional local writes, retry idempotency, and truthful evidence tracking.
 * Operations in R6 are stored locally by the configured development storage adapter.
 */

export type OperationId = string;
export type IdempotencyKey = string;

export type OperationType =
  | 'RECORD_RIDE_TELEMETRY'
  | 'REPORT_HAZARD'
  | 'POST_COMMUNITY_FEED'
  | 'UPDATE_GARAGE'
  | 'QUEUE_SOS_BREADCRUMB';

export type OperationState =
  | 'queued'      // Enqueued locally on device (truthful local observation)
  | 'sending'     // In active transit attempt
  | 'accepted'    // Future server-authoritative result (cannot be generated by local enqueue in R6)
  | 'rejected'    // Permanent client/validation error
  | 'conflicted'; // Conflict (version mismatch / 409)

export interface QueuedOperation<T = Record<string, unknown>> {
  operationId: OperationId;
  idempotencyKey: IdempotencyKey;
  operationType: OperationType;
  payload: T;
  state: OperationState;
  createdAtUtc: string;
  attemptCount: number;
  lastAttemptUtc?: string;
  lastErrorCode?: string;
  lastErrorMessage?: string;
}
